import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 * Created by employee on 7/25/16.
 */
public class CreateTables {

    protected void createTables(Connection connection)
            throws SQLException {
        PreparedStatement statement = connection.prepareStatement(
                "CREATE TABLE Categories" +
                        "(CategoryId int not null GENERATED BY DEFAULT AS IDENTITY, " +
                        "Name varchar(100), PRIMARY KEY(CategoryId))");
        statement.executeUpdate();
        statement = connection.prepareStatement(
                "CREATE TABLE Customers" +
                        "(CustomerId int not null GENERATED BY DEFAULT AS IDENTITY, " +
                        "CustomerName varchar(100) not null, " +
                        "PRIMARY KEY (CustomerId));");
        statement.executeUpdate();
        statement = connection.prepareStatement(
                "CREATE TABLE Purchases" +
                        "(PurchaseId int not null GENERATED BY DEFAULT AS IDENTITY, CustomerId int, " +
                        "DateTime TIMESTAMP, Cost decimal(7,2), PRIMARY KEY(PurchaseId))");
        statement.executeUpdate();
        statement = connection.prepareStatement(
                "CREATE TABLE Items" +
                        "(ItemId int not null GENERATED BY DEFAULT AS IDENTITY, " +
                        "ItemName varchar(100) not null, CategoryId int not null, " +
                        "Cost decimal(7,2) not null, " +
                        "PRIMARY KEY (ItemId), FOREIGN KEY (CategoryId) " +
                        "REFERENCES Categories(CategoryId));");
        statement.executeUpdate();
        statement = connection.prepareStatement(
                "CREATE TABLE ItemsInPurchase" +
                        "(PurchaseId int not null, ItemId int not null, " +
                        "ItemsNumber int not null, Price decimal(7,2) not null, " +
                        "FOREIGN KEY (ItemId) REFERENCES Items(ItemId), " +
                        "FOREIGN KEY (PurchaseId) REFERENCES Purchases(PurchaseId));");
        statement.executeUpdate();

        statement.close();
    }
}
