/**
 * Created by employee on 7/21/16.
 */

import entity.PurchaseRoster;
import dao.PurchaseRosterDao;
import org.junit.Before;
import org.junit.Test;

import java.sql.*;
import java.util.List;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class PurchaseRosterDaoTest {
    private PurchaseRosterDao purchaseListDao;
    private  SqlConnectionForTestImpl sqlConnectionForTest;

    @Before
    public void init() throws Exception {
        sqlConnectionForTest = new SqlConnectionForTestImpl();
        createTables(sqlConnectionForTest.getConnection());
        purchaseListDao = new PurchaseRosterDao(sqlConnectionForTest.getConnection());
    }

    private void createTables(Connection connection)
            throws SQLException {
        PreparedStatement statement = connection.prepareStatement(
                "CREATE TABLE PurchaseRoster"+
                "(PurchaseId int not null GENERATED BY DEFAULT AS IDENTITY, CustomerId int, " +
                "DateTime TIMESTAMP, Cost decimal(7,2))");
        statement.execute();
        statement.close();
    }

    @Test
    public void hasRecord() throws Exception {
        PurchaseRoster purchaseRoster = new PurchaseRoster("4,2016-07-29,20:15:30,50.50");
        purchaseRoster.setCustomerId(4);

        purchaseListDao.create(purchaseRoster);
        purchaseRoster = new PurchaseRoster("2,2016-07-29,20:15:30,50.50");
        purchaseListDao.create(purchaseRoster);

        List<PurchaseRoster> testCategories = purchaseListDao.getForCustomer(4);

        assertThat(testCategories.size(),is(1));
    }

}
